### ISSUE TITLE
install err

### ISSUE THREAD

**Issue by baron-tommy** [miao1007/gitbook-plugin-mermaid-cli#1]
version
```bash
tommy@tommy /V/w/gitbook-pg> gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3

tommy@tommy /V/w/gitbook-pg> npm -v
6.4.1

tommy@tommy /V/w/gitbook-pg> node -v
v10.10.0
```

log
```bash
info: installing plugin "mermaid-cli"
info: install plugin "mermaid-cli" (*) from NPM with version 1.0.10
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at spawn (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at lifecycle_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:131:3)
```

**Comment by miao1007** [comment]
It's something wrong with the chrome. I will release a new version without download chrome  tonight

**Comment by baron-tommy** [comment]
@miao1007 
谢谢🇨🇳

**Comment by miao1007** [comment]
Please reinstall with the new book.json

```json
{
  "plugins": ["mermaid-cli"],
  "pluginsConfig": {
    "mermaid-cli": {
      "chromeDir": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    },
  }
}
```
then

```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
# be sure to remove the old file
# rm node_modules/gitbook-plugin-mermaid-cli/
# install plugin
gitbook install
# run the gitbook
gitbook serve
```

**Comment by baron-tommy** [comment]
@miao1007 

```bash
tommy@tommy /V/w/gitbook-pg> rm -rf node_modules
tommy@tommy /V/w/gitbook-pg> ll
total 16
-rw-r--r--  1 tommy  staff    84B  9 10 20:19 README.md
drwxr-xr-x  3 tommy  staff   170B  9 10 20:13 book
-rw-r--r--  1 tommy  staff   719B  9 10 22:57 book.json
drwxr-xr-x  4 tommy  staff   136B  9 10 20:13 component

tommy@tommy /V/w/gitbook-pg> ll "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
-rwxrwxr-x  1 tommy  admin    19K  8  8 11:40 /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

err log
```bash
info: installing plugin "mermaid-cli"
runTopLevelLifecycles → 2 ▌ ╢██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░╟
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at spawn (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at lifecycle_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:131:3)
```

book.json
```json
{
    "root": "book",
    "plugins": [
        "-lunr", "-search", "search-pro",
        "-sharing",
        "hide-published-with",
        "page-toc",
        "summary",
        "chart",
        "copy-code-button",
        "plantuml-svg",
        "mermaid-cli"
    ],
    "pluginsConfig": {
        "page-toc": {
            "selector": ".markdown-section h1, .markdown-section h2, .markdown-section h3, .markdown-section h4",
            "position": "before-first",
            "showByDefault": true
          },
          "chart": {
            "type": "highcharts"
          },
          "mermaid-cli": {
            "chromeDir": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
          }
      }
}
```

**Comment by baron-tommy** [comment]
minimal

book.json
```
{
    "root": "book",
    "plugins": [
        "mermaid-cli"
    ],
    "pluginsConfig": {
          "mermaid-cli": {
            "chromeDir": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
          }
      }
}
```

```bash
tommy@tommy /V/w/gitbook-pg> rm -rf node_modules
tommy@tommy /V/w/gitbook-pg> gitbook install
info: installing 1 plugins using npm@3.9.2
info:
info: installing plugin "mermaid-cli"
info: install plugin "mermaid-cli" (*) from NPM with version 1.0.12
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at spawn (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at lifecycle_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:131:3)
```

**Comment by baron-tommy** [comment]
`https://github.com/GitbookIO/plugin-autocover/issues/21`
double quart -> single quart ??

**Comment by miao1007** [comment]
The error "Error: spawn E2BIG" seems to caused by eval js file in gitbook, I passed by ignore the chrome installation script.

are you turn on 

```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```

**Comment by baron-tommy** [comment]
```bash
tommy@tommy /V/w/gitbook-pg> echo $PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
true
```

**Comment by baron-tommy** [comment]
谢谢你的调查

**Comment by miao1007** [comment]
run `gitbook install` twice seem to install successfully

**Comment by baron-tommy** [comment]
perfect

```bash
tommy@tommy /V/w/gitbook-pg> gitbook install
info: installing 1 plugins using npm@3.9.2
info:
info: installing plugin "mermaid-cli"
info: install plugin "mermaid-cli" (*) from NPM with version 1.0.12
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at spawn (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at lifecycle_ (/Users/tommy/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:131:3)
```

```bash
tommy@tommy /V/w/gitbook-pg> gitbook install
info: installing 1 plugins using npm@3.9.2
info:
info: installing plugin "mermaid-cli"
info: install plugin "mermaid-cli" (*) from NPM with version 1.0.12
info: >> plugin "mermaid-cli" installed with success
tommy@tommy /V/w/gitbook-pg>
```
