### ISSUE TITLE
PluginError: Error with plugin "mermaid-cli": Unexpected token function

### ISSUE THREAD

**Issue by wuxingzhong** [miao1007/gitbook-plugin-mermaid-cli#5]
PluginError: Error with plugin "mermaid-cli": Unexpected token function
    at createError (/root/.gitbook/versions/3.2.3/node_modules/error/typed.js:31:22)
    at new createError (/root/.gitbook/versions/3.2.3/node_modules/error/wrapped.js:88:19)
    at /root/.gitbook/versions/3.2.3/lib/plugins/loadPlugin.js:67:23
    at _fulfilled (/root/.gitbook/versions/3.2.3/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/root/.gitbook/versions/3.2.3/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/root/.gitbook/versions/3.2.3/node_modules/q/q.js:796:13)
    at /root/.gitbook/versions/3.2.3/node_modules/q/q.js:857:14
    at runSingle (/root/.gitbook/versions/3.2.3/node_modules/q/q.js:137:13)
    at flush (/root/.gitbook/versions/3.2.3/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by wuxingzhong** [comment]
gitbook3.2.3

**Comment by miao1007** [comment]
clone my project, then

```sh
npm install
# edit the `withBookJson` in the js
# then run
node spec/simple.js
```

**Comment by wuxingzhong** [comment]
chromeDir or chromeArgs error?

```
＃open gitbook-tester debug
export DEBUG=true
node spec/simple.js
```
the same error

**Comment by miao1007** [comment]
chromeArgs: can be empty.
chromeDir: chrome binary dir. If you are using windows, make sure add escape character
```
"D://xxx//xx.exe"
```

rather than 

```
D:/xxx/xx.exe
```
